settings:
  chat-status: true
  slowdown: 3

connect-messages:
  # Set "" to disable message
  join: "&8(&a+&8) &7Gracz &f{player} &7dołączył do gry!"
  quit: "&8(&c-&8) &7Gracz &f{player} &7wyszedł z gry!"
  first-join: "&8(&d+&8) &7Gracz &f{player} &7dołączył do gry po raz pierwszy!"

adminchat:
  format: "&8[&4&lAdminChat&8] &c{player}&f: &7{message}"

censor:
  enabled: true
  replacer: "*"
  bad-words:
    - "kurwa"
    - "chuj"
    - "japierdole"

messages:
  chat-enabled: "&7Czat został &awłączony&7!"
  chat-disabled: "&7Czat został &cwyłączony&7!"
  chat-cleared: "&7Czat został &fwyczyszczony&7!"
  chat-slowed: "&7Spowolnienie czatu zostało ustawione na &f{time}&7!"
  chat-locked: "&cWyłączyłeś widoczność czatu serwera!"
  chat-unlocked: "&aWłączyłeś widoczność czatu serwera!"
  reload-success: "&aPomyślnie przeładowano konfigurację pluginu!"
  missing-permission: "&cNie masz wymaganych uprawnień! &7({permission})"
  is-console: "&cNie możesz użyć tego z poziomu konsoli!"
  locked-alert: "&cNie możesz pisać przy zablokowanym czacie!"
  slowdown-alert: "&cNastępną wiadomość możesz napisać za &7{time} &csekund!"
  invalid-usage: "&cPoprawne użycie: &7{usage}"
  invalid-time: "&cNieprawidłowy czas!"
  chat-already-enabled: "&cCzat jest już włączony!"
  chat-already-disabled: "&cCzat jest już wyłączony!"